INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (seq_business_unit.nextval,'EN vulputate velit eu sem.','FR integer sem elit, pharetra','pretium','Phasellus',3);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (seq_business_unit.nextval,'EN in nec orci. Donec nibh. Quisque nonummy ipsum non','FR mi. Aliquam','ut','enim',1);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (seq_business_unit.nextval,'EN tincidunt dui augue eu tellus. Phasellus','FR malesuada fames ac','enim.','quam',2);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (seq_business_unit.nextval,'EN luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec','FR non dui nec','nulla.','arcu',2);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (seq_business_unit.nextval,'EN ac orci. Ut semper pretium neque.','FR natoque penatibus et magnis dis parturient montes, nascetur','montes,','magna.',2);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (seq_business_unit.nextval,'EN dui, nec tempus mauris','FR vulputate, risus a ultricies','magna.','quam.',2);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (seq_business_unit.nextval,'EN ultrices','FR aliquam ultrices iaculis odio.','Duis','sit',2);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (seq_business_unit.nextval,'EN tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis,','FR volutpat ornare, facilisis eget, ipsum.','ullamcorper,','Nam',2);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (seq_business_unit.nextval,'EN nibh.','FR ultrices posuere cubilia Curae; Phasellus ornare. Fusce','turpis','arcu.',2);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (seq_business_unit.nextval,'EN mauris','FR facilisis','non,','ligula.',1);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (seq_business_unit.nextval,'EN et, rutrum non, hendrerit id,','FR ornare, elit elit fermentum risus, at fringilla purus mauris','Donec','felis',2);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (seq_business_unit.nextval,'EN scelerisque sed, sapien. Nunc','FR eu','vitae','Donec',2);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (seq_business_unit.nextval,'EN ante blandit viverra. Donec tempus, lorem fringilla ornare placerat,','FR id, erat. Etiam vestibulum massa','purus','posuere',3);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (seq_business_unit.nextval,'EN parturient montes, nascetur ridiculus','FR tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem','Nunc','ut',1);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (seq_business_unit.nextval,'EN pellentesque,','FR arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras','Duis','egestas.',2);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (seq_business_unit.nextval,'EN tellus sem mollis dui, in sodales','FR donec','sed','porta',2);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (seq_business_unit.nextval,'EN ac, feugiat non, lobortis quis, pede. Suspendisse','FR nostra, per inceptos','diam.','Mauris',2);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (seq_business_unit.nextval,'EN tristique pellentesque, tellus sem mollis','FR aenean massa. Integer vitae nibh. Donec','Sed','Duis',2);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (seq_business_unit.nextval,'EN aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non','FR quisque varius. Nam porttitor scelerisque neque. Nullam nisl.','pellentesque','velit',2);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (seq_business_unit.nextval,'EN non, luctus sit amet, faucibus ut, nulla.','FR luctus.','a','eu',3);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (seq_business_unit.nextval,'EN orci lacus','FR pede. Praesent eu dui. Cum sociis natoque penatibus et','hendrerit','nascetur',1);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (seq_business_unit.nextval,'EN enim. Etiam imperdiet dictum magna. Ut tincidunt orci','FR montes,','non,','odio',3);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (seq_business_unit.nextval,'EN ullamcorper,','FR proin non massa non ante bibendum','Pellentesque','luctus',1);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (seq_business_unit.nextval,'EN eget laoreet posuere, enim nisl elementum purus, accumsan interdum','FR auctor non, feugiat nec, diam. Duis mi enim,','dapibus','odio.',1);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (seq_business_unit.nextval,'EN nulla. In tincidunt congue turpis.','FR nulla semper tellus id nunc interdum','nulla','velit',3);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (seq_business_unit.nextval,'EN cursus et, magna. Praesent interdum ligula','FR mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim.','velit.','feugiat.',2);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (seq_business_unit.nextval,'EN amet, dapibus id, blandit at,','FR id, ante. Nunc mauris','risus','imperdiet',3);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (seq_business_unit.nextval,'EN a, aliquet vel, vulputate eu,','FR dictum cursus. Nunc mauris elit, dictum eu,','Curabitur','pede.',2);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (seq_business_unit.nextval,'EN arcu. Vestibulum ante ipsum primis in faucibus orci','FR in, hendrerit consectetuer, cursus et, magna.','lectus','amet',1);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (seq_business_unit.nextval,'EN elementum','FR posuere cubilia Curae; Donec tincidunt. Donec','ultrices.','arcu.',1);

UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 15 WHERE ID = 1;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 1 WHERE ID = 2;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 3 WHERE ID = 3;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 11 WHERE ID = 4;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 14 WHERE ID = 5;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 1 WHERE ID = 6;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 16 WHERE ID = 7;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 20 WHERE ID = 8;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 3 WHERE ID = 9;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 24 WHERE ID = 10;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 2 WHERE ID = 11;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 18 WHERE ID = 12;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 8 WHERE ID = 13;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 8 WHERE ID = 14;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 6 WHERE ID = 15;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 26 WHERE ID = 16;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 6 WHERE ID = 17;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 22 WHERE ID = 18;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 27 WHERE ID = 19;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 15 WHERE ID = 20;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 25 WHERE ID = 21;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 16 WHERE ID = 22;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 25 WHERE ID = 23;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 18 WHERE ID = 24;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 18 WHERE ID = 25;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 26 WHERE ID = 26;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 18 WHERE ID = 27;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 30 WHERE ID = 28;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 16 WHERE ID = 29;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 5 WHERE ID = 30;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 22 WHERE ID = 31;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 22 WHERE ID = 32;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 16 WHERE ID = 33;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 16 WHERE ID = 34;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 24 WHERE ID = 35;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 24 WHERE ID = 36;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 21 WHERE ID = 37;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 29 WHERE ID = 38;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 25 WHERE ID = 39;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 2 WHERE ID = 40;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 23 WHERE ID = 41;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 1 WHERE ID = 42;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 29 WHERE ID = 43;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 16 WHERE ID = 44;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 24 WHERE ID = 45;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 15 WHERE ID = 46;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 10 WHERE ID = 47;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 16 WHERE ID = 48;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 2 WHERE ID = 49;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 30 WHERE ID = 50;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 17 WHERE ID = 51;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 18 WHERE ID = 52;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 12 WHERE ID = 53;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 27 WHERE ID = 54;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 25 WHERE ID = 55;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 30 WHERE ID = 56;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 20 WHERE ID = 57;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 18 WHERE ID = 58;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 1 WHERE ID = 59;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 5 WHERE ID = 60;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 18 WHERE ID = 61;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 22 WHERE ID = 62;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 15 WHERE ID = 63;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 28 WHERE ID = 64;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 8 WHERE ID = 65;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 25 WHERE ID = 66;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 3 WHERE ID = 67;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 23 WHERE ID = 68;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 13 WHERE ID = 69;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 11 WHERE ID = 70;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 25 WHERE ID = 71;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 1 WHERE ID = 72;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 19 WHERE ID = 73;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 24 WHERE ID = 74;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 10 WHERE ID = 75;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 11 WHERE ID = 76;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 25 WHERE ID = 77;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 9 WHERE ID = 78;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 16 WHERE ID = 79;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 22 WHERE ID = 80;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 20 WHERE ID = 81;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 4 WHERE ID = 82;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 24 WHERE ID = 83;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 1 WHERE ID = 84;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 28 WHERE ID = 85;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 25 WHERE ID = 86;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 19 WHERE ID = 87;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 13 WHERE ID = 88;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 26 WHERE ID = 89;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 26 WHERE ID = 90;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 3 WHERE ID = 91;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 27 WHERE ID = 92;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 30 WHERE ID = 93;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 30 WHERE ID = 94;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 15 WHERE ID = 95;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 2 WHERE ID = 96;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 17 WHERE ID = 97;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 8 WHERE ID = 98;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 15 WHERE ID = 99;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 4 WHERE ID = 100;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 11 WHERE ID = 101;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 24 WHERE ID = 102;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 5 WHERE ID = 103;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 22 WHERE ID = 104;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 22 WHERE ID = 105;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 9 WHERE ID = 106;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 19 WHERE ID = 107;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 3 WHERE ID = 108;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 16 WHERE ID = 109;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 22 WHERE ID = 110;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 29 WHERE ID = 111;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 19 WHERE ID = 112;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 14 WHERE ID = 113;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 15 WHERE ID = 114;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 6 WHERE ID = 115;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 13 WHERE ID = 116;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 13 WHERE ID = 117;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 30 WHERE ID = 118;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 17 WHERE ID = 119;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 2 WHERE ID = 120;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 19 WHERE ID = 121;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 2 WHERE ID = 122;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 13 WHERE ID = 123;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 19 WHERE ID = 124;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 1 WHERE ID = 125;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 2 WHERE ID = 126;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 17 WHERE ID = 127;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 16 WHERE ID = 128;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 16 WHERE ID = 129;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 20 WHERE ID = 130;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 22 WHERE ID = 131;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 28 WHERE ID = 132;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 1 WHERE ID = 133;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 15 WHERE ID = 134;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 30 WHERE ID = 135;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 20 WHERE ID = 136;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 6 WHERE ID = 137;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 6 WHERE ID = 138;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 19 WHERE ID = 139;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 6 WHERE ID = 140;
UPDATE FUNDING_OPPORTUNITY SET BUSINESS_UNIT_ID = 6 WHERE ID = 141;




















